export const GAME_LEVELS = [
  {
    id: 1,
    title: 'Iniciar un Repositorio',
    description: '¿Qué comando utilizas para crear un nuevo repositorio Git?',
    scenario:
      'Tienes una carpeta de proyecto vacía y necesitas inicializar Git.',
    correctCommands: ['git init'],
    hint: "El comando comienza con 'git' y es muy simple. Se usa para inicializar.",
    points: 10,
    medal: '🌟 Primer Paso',
  },
  {
    id: 2,
    title: 'Ver el Estado',
    description:
      '¿Cuál es el comando para ver el estado actual del repositorio?',
    scenario:
      'Acabas de crear archivos en tu proyecto y quieres ver qué cambios hay.',
    correctCommands: ['git status'],
    hint: "Es 'git' seguido de una palabra que significa 'estado' en inglés.",
    points: 10,
    medal: '📊 Observador',
  },
  {
    id: 3,
    title: 'Agregar Archivos',
    description:
      '¿Cuál es el comando para agregar archivos al área de preparación?',
    scenario:
      'Tienes archivos modificados y quieres prepararlos para hacer commit.',
    correctCommands: ['git add .', 'git add *', 'git add archivo.txt'],
    hint: "Es 'git add' seguido de un patrón. Puedes usar '.' para todos los archivos.",
    points: 15,
    medal: '📝 Preparador',
  },
  {
    id: 4,
    title: 'Hacer Commit',
    description: '¿Cuál es el comando para guardar cambios con un mensaje?',
    scenario:
      'Tus cambios están preparados y quieres crear un punto de guardado.',
    correctCommands: [
      'git commit -m "mensaje"',
      'git commit',
      "git commit -m 'mensaje'",
    ],
    hint: "Es 'git commit'. Necesitas agregar -m para el mensaje y un texto descriptivo.",
    points: 20,
    medal: '💾 Guardador',
  },
  {
    id: 5,
    title: 'Ver el Historial',
    description: '¿Cuál es el comando para ver el historial de commits?',
    scenario:
      'Quieres revisar todos los cambios que has realizado hasta ahora.',
    correctCommands: ['git log'],
    hint: "Es 'git' seguido de una palabra que significa 'registro' en inglés.",
    points: 10,
    medal: '📜 Historiador',
  },
  {
    id: 6,
    title: 'Crear una Rama',
    description: '¿Cuál es el comando para crear y cambiar a una nueva rama?',
    scenario:
      'Quieres trabajar en una nueva característica sin afectar la rama principal.',
    correctCommands: [
      'git checkout -b nombre-rama',
      'git switch -c nombre-rama',
    ],
    hint: "Puedes usar 'git checkout -b' o 'git switch -c' seguido del nombre de la rama.",
    points: 20,
    medal: '🌿 Cultivador',
  },
  {
    id: 7,
    title: 'Cambiar de Rama',
    description: '¿Cuál es el comando para cambiar a una rama existente?',
    scenario:
      'Tienes varias ramas y necesitas cambiar a la rama principal (main).',
    correctCommands: [
      'git checkout main',
      'git checkout master',
      'git switch main',
    ],
    hint: "Usa 'git checkout' o 'git switch' seguido del nombre de la rama.",
    points: 15,
    medal: '🔄 Navegador',
  },
  {
    id: 8,
    title: 'Fusionar Ramas',
    description:
      '¿Cuál es el comando para fusionar una rama en la rama actual?',
    scenario:
      'Terminaste de trabajar en una rama y quieres integrar los cambios.',
    correctCommands: ['git merge nombre-rama'],
    hint: "Es 'git merge' seguido del nombre de la rama que quieres fusionar.",
    points: 25,
    medal: '🔗 Fusionador',
  },
  {
    id: 9,
    title: 'Enviar Cambios',
    description:
      '¿Cuál es el comando para enviar cambios a un repositorio remoto?',
    scenario:
      'Completaste tu trabajo local y quieres subirlo a GitHub o similar.',
    correctCommands: [
      'git push',
      'git push origin main',
      'git push origin master',
    ],
    hint: "Es 'git push' (y opcionalmente el nombre del remoto y rama).",
    points: 25,
    medal: '🚀 Lanzador',
  },
  {
    id: 10,
    title: 'Obtener Cambios',
    description:
      '¿Cuál es el comando para obtener cambios del repositorio remoto?',
    scenario: 'Tu compañero subió cambios y quieres actualizar tu copia local.',
    correctCommands: [
      'git pull',
      'git pull origin main',
      'git pull origin master',
    ],
    hint: "Es 'git pull' (y opcionalmente el nombre del remoto y rama).",
    points: 25,
    medal: '📥 Actualizador',
  },
  {
    id: 11,
    title: 'Deshacer Cambios no Guardados',
    description: '¿Cuál es el comando para descartar cambios no guardados?',
    scenario: 'Hiciste cambios que no quieres guardar y quieres revertirlos.',
    correctCommands: ['git checkout -- archivo.txt', 'git restore archivo.txt'],
    hint: "Usa 'git checkout --' o 'git restore' seguido del nombre del archivo.",
    points: 20,
    medal: '↩️ Revisor',
  },
  {
    id: 12,
    title: 'Eliminar Rama Local',
    description: '¿Cuál es el comando para eliminar una rama local?',
    scenario:
      'Terminaste de trabajar en una rama y quieres limpiar tu repositorio.',
    correctCommands: ['git branch -d nombre-rama', 'git branch -D nombre-rama'],
    hint: "Usa 'git branch -d' o '-D' seguido del nombre de la rama.",
    points: 15,
    medal: '🗑️ Limpiador',
  },
  {
    id: 13,
    title: 'Listar Ramas',
    description: '¿Cuál es el comando para ver todas las ramas?',
    scenario: 'Quieres saber todas las ramas disponibles en tu repositorio.',
    correctCommands: ['git branch', 'git branch -a'],
    hint: "Es 'git branch' (usa '-a' para ver todas incluyendo remotas).",
    points: 10,
    medal: '📋 Catalogador',
  },
  {
    id: 14,
    title: 'Rebasar (Rebase)',
    description: '¿Cuál es el comando para reaplicar cambios sobre otra rama?',
    scenario: 'Quieres linealizar el historial antes de hacer merge.',
    correctCommands: ['git rebase main', 'git rebase master'],
    hint: "Es 'git rebase' seguido del nombre de la rama base.",
    points: 30,
    medal: '⛓️ Rebasador',
  },
  {
    id: 15,
    title: 'Ver Diferencias',
    description: '¿Cuál es el comando para ver las diferencias en archivos?',
    scenario: 'Quieres comparar cambios antes de hacer commit.',
    correctCommands: ['git diff', 'git diff archivo.txt'],
    hint: "Es 'git diff' (opcionalmente con nombre de archivo).",
    points: 15,
    medal: '🔍 Comparador',
  },
  {
    id: 16,
    title: 'Etiquetar un Commit',
    description: '¿Cuál es el comando para crear una etiqueta (tag)?',
    scenario: 'Quieres marcar un commit importante como versión 1.0.',
    correctCommands: ['git tag v1.0', 'git tag nombre-tag'],
    hint: "Es 'git tag' seguido del nombre de la etiqueta.",
    points: 20,
    medal: '🏷️ Etiquetador',
  },
  {
    id: 17,
    title: 'Resetear a un Commit',
    description: '¿Cuál es el comando para volver a un commit anterior?',
    scenario:
      'Quieres deshacer los últimos commits manteniéndolos en el historial.',
    correctCommands: [
      'git reset --soft id-commit',
      'git reset --hard id-commit',
    ],
    hint: "Es 'git reset' con opciones --soft o --hard.",
    points: 25,
    medal: '⏮️ Retrocedor',
  },
  {
    id: 18,
    title: 'Cambiar Nombre a la Rama',
    description: '¿Cuál es el comando para renombrar una rama?',
    scenario: 'Te equivocaste en el nombre de la rama y quieres cambiarla.',
    correctCommands: [
      'git branch -m nombre-nuevo',
      'git branch -m nombre-viejo nombre-nuevo',
    ],
    hint: "Usa 'git branch -m' para renombrar.",
    points: 15,
    medal: '✏️ Renombrador',
  },
  {
    id: 19,
    title: 'Copiar un Commit (Cherry-pick)',
    description: '¿Cuál es el comando para aplicar un commit específico?',
    scenario: 'Necesitas un commit de otra rama sin hacer merge completo.',
    correctCommands: ['git cherry-pick id-commit'],
    hint: "Es 'git cherry-pick' seguido del ID del commit.",
    points: 25,
    medal: '🍒 Recolector',
  },
  {
    id: 20,
    title: 'Ver Ramas Remotas',
    description: '¿Cuál es el comando para ver las ramas del servidor remoto?',
    scenario: 'Quieres saber qué ramas tiene tu equipo en el servidor.',
    correctCommands: ['git branch -r', 'git branch --remote'],
    hint: "Usa 'git branch -r' o '--remote'.",
    points: 15,
    medal: '🌐 Explorador',
  },
  {
    id: 21,
    title: 'Clonar un Repositorio',
    description: '¿Cuál es el comando para descargar un repositorio remoto?',
    scenario: 'Quieres trabajar en un proyecto que está en GitHub.',
    correctCommands: [
      'git clone url',
      'git clone https://github.com/usuario/repo.git',
    ],
    hint: "Es 'git clone' seguido de la URL del repositorio.",
    points: 20,
    medal: '📦 Clonador',
  },
  {
    id: 22,
    title: 'Agregar Repositorio Remoto',
    description: '¿Cuál es el comando para vincular un repositorio remoto?',
    scenario: 'Necesitas agregar un nuevo servidor remoto a tu proyecto.',
    correctCommands: ['git remote add origin url', 'git remote add nombre url'],
    hint: "Es 'git remote add' seguido del nombre y URL.",
    points: 20,
    medal: '🔗 Vinculador',
  },
  {
    id: 23,
    title: 'Ver Repositorios Remotos',
    description: '¿Cuál es el comando para listar los repositorios remotos?',
    scenario: 'Quieres saber qué servidores remotos tienes configurados.',
    correctCommands: ['git remote', 'git remote -v'],
    hint: "Es 'git remote' (usa '-v' para ver URLs).",
    points: 10,
    medal: '📡 Detector',
  },
  {
    id: 24,
    title: 'Traer Cambios del Remoto',
    description: '¿Cuál es el comando para descargar cambios sin fusionar?',
    scenario:
      'Quieres ver qué hay en el servidor sin integrar automáticamente.',
    correctCommands: ['git fetch', 'git fetch origin'],
    hint: "Es 'git fetch' (sin fusionar como lo haría pull).",
    points: 20,
    medal: '⬇️ Descargador',
  },
  {
    id: 25,
    title: 'Guardar Trabajo Temporal (Stash)',
    description: '¿Cuál es el comando para guardar cambios temporalmente?',
    scenario: 'Necesitas cambiar de rama pero tienes cambios sin guardar.',
    correctCommands: ['git stash', 'git stash save'],
    hint: "Es 'git stash' para guardar cambios en el escritorio temporal.",
    points: 20,
    medal: '💼 Guardatodo',
  },
  {
    id: 26,
    title: 'Recuperar Trabajo Guardado (Stash Pop)',
    description: '¿Cuál es el comando para recuperar cambios guardados?',
    scenario: 'Guardaste cambios con stash y ahora quieres recuperarlos.',
    correctCommands: ['git stash pop', 'git stash apply'],
    hint: "Usa 'git stash pop' o 'git stash apply'.",
    points: 15,
    medal: '📤 Recuperador',
  },
  {
    id: 27,
    title: 'Renombrar o Mover Archivo',
    description: '¿Cuál es el comando para renombrar un archivo con Git?',
    scenario: 'Quieres renombrar archivo.txt a nombre-nuevo.txt.',
    correctCommands: ['git mv archivo.txt nombre-nuevo.txt'],
    hint: "Es 'git mv' seguido del nombre viejo y nuevo.",
    points: 15,
    medal: '🎯 Movedor',
  },
  {
    id: 28,
    title: 'Eliminar Archivo con Git',
    description: '¿Cuál es el comando para eliminar un archivo en Git?',
    scenario: 'Quieres eliminar un archivo del repositorio.',
    correctCommands: ['git rm archivo.txt', 'git rm -r carpeta/'],
    hint: "Es 'git rm' seguido del nombre del archivo (usa -r para carpetas).",
    points: 15,
    medal: '❌ Eliminador',
  },
  {
    id: 29,
    title: 'Ver Autoría de Líneas (Blame)',
    description: '¿Cuál es el comando para ver quién escribió cada línea?',
    scenario: 'Quieres saber quién escribió una línea específica del código.',
    correctCommands: ['git blame archivo.txt'],
    hint: "Es 'git blame' seguido del nombre del archivo.",
    points: 20,
    medal: '🔎 Investigador',
  },
  {
    id: 30,
    title: 'Ver Archivos de un Commit',
    description: '¿Cuál es el comando para listar archivos en un commit?',
    scenario:
      'Quieres saber qué archivos se modificaron en un commit específico.',
    correctCommands: [
      'git show --name-only id-commit',
      'git diff-tree --no-commit-id --name-only -r id-commit',
    ],
    hint: "Usa 'git show --name-only' o 'git diff-tree' con el ID del commit.",
    points: 20,
    medal: '📂 Inspector',
  },
  {
    id: 31,
    title: 'Crear Rama y Cambiar (Switcher)',
    description: '¿Cuál es el comando moderno para crear y cambiar rama?',
    scenario: 'Usando git moderno, necesitas crear feature/nueva-funcion.',
    correctCommands: ['git switch -c feature/nueva-funcion'],
    hint: "El comando moderno es 'git switch -c' para crear y cambiar.",
    points: 15,
    medal: '⚡ Modernizador',
  },
  {
    id: 32,
    title: 'Enmendar Último Commit',
    description: '¿Cuál es el comando para modificar el último commit?',
    scenario: 'Cometiste un error en el último commit y quieres corregirlo.',
    correctCommands: [
      'git commit --amend',
      'git commit --amend -m "nuevo mensaje"',
    ],
    hint: "Es 'git commit --amend' para modificar el commit anterior.",
    points: 25,
    medal: '✏️ Enmendador',
  },
  {
    id: 33,
    title: 'Listar Cambios por Autor',
    description: '¿Cuál es el comando para ver commits de un autor específico?',
    scenario: 'Quieres ver todos los commits de un compañero de equipo.',
    correctCommands: [
      'git log --author=nombre',
      'git log --author="nombre completo"',
    ],
    hint: "Usa 'git log --author=' seguido del nombre.",
    points: 20,
    medal: '👤 Seguidor',
  },
  {
    id: 34,
    title: 'Buscar en Commits (Grep)',
    description: '¿Cuál es el comando para buscar texto en commits?',
    scenario: 'Necesitas encontrar un commit que mencione "bug" o "fix".',
    correctCommands: ['git log -S "texto"', 'git log --grep="patron"'],
    hint: "Usa 'git log -S' o '--grep' con el texto a buscar.",
    points: 20,
    medal: '🔎 Buscador',
  },
  {
    id: 35,
    title: 'Ver Cambios Preparados',
    description: '¿Cuál es el comando para ver diferencias en el staging area?',
    scenario: 'Quieres revisar los cambios que preparaste antes de commit.',
    correctCommands: ['git diff --staged', 'git diff --cached'],
    hint: "Usa 'git diff --staged' o '--cached'.",
    points: 15,
    medal: '📋 Revisor',
  },
  {
    id: 36,
    title: 'Configurar Usuario',
    description: '¿Cuál es el comando para establecer tu nombre de usuario?',
    scenario: 'Es tu primer commit y necesitas configurar tu identidad en Git.',
    correctCommands: [
      'git config --global user.name "nombre"',
      'git config user.name "nombre"',
    ],
    hint: "Es 'git config --global user.name' seguido de tu nombre entre comillas.",
    points: 10,
    medal: '🎫 Identificador',
  },
  {
    id: 37,
    title: 'Configurar Email',
    description: '¿Cuál es el comando para establecer tu email en Git?',
    scenario:
      'Necesitas configurar tu email para que se registre en los commits.',
    correctCommands: [
      'git config --global user.email "email@ejemplo.com"',
      'git config user.email "email@ejemplo.com"',
    ],
    hint: "Es 'git config --global user.email' seguido de tu email entre comillas.",
    points: 10,
    medal: '📧 Configurador',
  },
  {
    id: 38,
    title: 'Ver Configuración',
    description: '¿Cuál es el comando para ver la configuración actual?',
    scenario: 'Quieres verificar que tu nombre y email están correctos.',
    correctCommands: ['git config --list', 'git config --global --list'],
    hint: "Es 'git config --list' (usa --global para ver todo).",
    points: 10,
    medal: '⚙️ Configurista',
  },
  {
    id: 39,
    title: 'Ignorar Archivos (.gitignore)',
    description: '¿Qué archivo creas para indicar qué no trackear?',
    scenario: 'Quieres que Git ignore archivos como node_modules o .env.',
    correctCommands: ['crear .gitignore', '.gitignore', 'archivo .gitignore'],
    hint: "Crea un archivo llamado '.gitignore' en la raíz del proyecto.",
    points: 15,
    medal: '🚫 Ignorador',
  },
  {
    id: 40,
    title: 'Crear Archivo de Alias',
    description: '¿Cómo configurarías un alias para abreviar comandos?',
    scenario: 'Quieres que "git co" sea alias de "git checkout".',
    correctCommands: [
      'git config --global alias.co checkout',
      'git config alias.co checkout',
    ],
    hint: "Usa 'git config --global alias.nombre comando'.",
    points: 15,
    medal: '🎯 Abridor',
  },
  {
    id: 41,
    title: 'Ver Archivo Específico en Commit',
    description:
      '¿Cuál es el comando para ver un archivo en un commit anterior?',
    scenario: 'Quieres ver cómo se veía app.js en el commit abc123.',
    correctCommands: [
      'git show abc123:app.js',
      'git show commit-id:archivo.txt',
    ],
    hint: "Es 'git show' seguido de 'commit-id:archivo'.",
    points: 20,
    medal: '📄 Visualizador',
  },
  {
    id: 42,
    title: 'Contar Commits',
    description: '¿Cuál es el comando para contar cuántos commits hay?',
    scenario: 'Necesitas saber el total de commits en tu rama.',
    correctCommands: ['git rev-list --count HEAD', 'git log --oneline | wc -l'],
    hint: "Usa 'git rev-list --count HEAD'.",
    points: 15,
    medal: '🔢 Contador',
  },
  {
    id: 43,
    title: 'Obtener Último Commit',
    description: '¿Cuál es el comando para ver solo el último commit?',
    scenario: 'Solo necesitas ver en qué trabajaste más recientemente.',
    correctCommands: ['git log -1', 'git log --max-count=1'],
    hint: "Usa 'git log -1' para ver solo 1 commit.",
    points: 10,
    medal: '📍 Localizador',
  },
  {
    id: 44,
    title: 'Formato Personalizado del Log',
    description: '¿Cuál es el comando para ver log con formato personalizado?',
    scenario: 'Quieres ver solo el autor y el mensaje en formato corto.',
    correctCommands: [
      'git log --pretty=format:"%an - %s"',
      'git log --format="%an - %s"',
    ],
    hint: "Usa '--pretty=format:' o '--format:' con placeholders.",
    points: 20,
    medal: '🎨 Formateador',
  },
  {
    id: 45,
    title: 'Ver Commits desde Fecha',
    description:
      '¿Cuál es el comando para ver commits desde una fecha específica?',
    scenario: 'Necesitas cambios del último mes.',
    correctCommands: [
      'git log --since="2024-11-02"',
      'git log --after="30 days ago"',
    ],
    hint: "Usa '--since=' o '--after=' con la fecha.",
    points: 20,
    medal: '📅 Cronólogo',
  },
  {
    id: 46,
    title: 'Ver Diferencias entre Commits',
    description: '¿Cuál es el comando para comparar dos commits?',
    scenario: 'Quieres ver qué cambió entre abc123 y def456.',
    correctCommands: ['git diff abc123 def456', 'git diff abc123..def456'],
    hint: "Es 'git diff' seguido de dos commit IDs.",
    points: 20,
    medal: '⚖️ Comparador',
  },
  {
    id: 47,
    title: 'Ver Cambios no Enviados',
    description: '¿Cuál es el comando para ver commits locales no enviados?',
    scenario: 'Quieres ver qué commits harías push.',
    correctCommands: [
      'git log origin/main..main',
      'git log origin/master..master',
    ],
    hint: "Usa 'git log origin/rama..rama'.",
    points: 20,
    medal: '📤 Emisor',
  },
  {
    id: 48,
    title: 'Ver Cambios Remotos No Obtenidos',
    description: '¿Cuál es el comando para ver commits remotos no obtenidos?',
    scenario: 'Quieres ver qué cambios el equipo hizo que aún no tienes.',
    correctCommands: [
      'git log main..origin/main',
      'git log master..origin/master',
    ],
    hint: "Usa 'git log rama..origin/rama'.",
    points: 20,
    medal: '⬇️ Receptor',
  },
  {
    id: 49,
    title: 'Revertir un Commit Específico',
    description:
      '¿Cuál es el comando para crear un nuevo commit que deshace otro?',
    scenario: 'Cometiste un error hace 3 commits y quieres deshacerlo.',
    correctCommands: ['git revert abc123', 'git revert HEAD~2'],
    hint: "Es 'git revert' seguido del commit a deshacer.",
    points: 25,
    medal: '↩️ Revertidor',
  },
  {
    id: 50,
    title: 'Resetear Rama a Commit Anterior',
    description:
      '¿Cuál es el comando para volver a un commit anterior (destructivo)?',
    scenario: 'Quieres eliminar los últimos 3 commits completamente.',
    correctCommands: ['git reset --hard HEAD~3', 'git reset --hard abc123'],
    hint: "Usa 'git reset --hard' con el commit destino.",
    points: 30,
    medal: '💥 Destructivo',
  },
  {
    id: 51,
    title: 'Resetear Suave (Soft)',
    description:
      '¿Cuál es el comando para deshacer commits manteniendo cambios?',
    scenario:
      'Quieres deshacer un commit pero mantener los cambios en staging.',
    correctCommands: ['git reset --soft HEAD~1', 'git reset --soft abc123'],
    hint: "Usa 'git reset --soft' para mantener los cambios.",
    points: 20,
    medal: '🟢 Suave',
  },
  {
    id: 52,
    title: 'Resetear Mixto (Mixed)',
    description: '¿Cuál es el comando para deshacer commits sin staging?',
    scenario:
      'Quieres deshacer un commit y los cambios quedan en working directory.',
    correctCommands: ['git reset --mixed HEAD~1', 'git reset HEAD~1'],
    hint: "Usa 'git reset --mixed' o solo 'git reset'.",
    points: 20,
    medal: '🟡 Mixto',
  },
  {
    id: 53,
    title: 'Reflog (Registro de Cambios HEAD)',
    description:
      '¿Cuál es el comando para ver el historial de cambios de HEAD?',
    scenario:
      'Accidentalmente reseteaste y quieres recuperar el commit anterior.',
    correctCommands: ['git reflog', 'git reflog show'],
    hint: "Es 'git reflog', muy útil para recuperar commits 'perdidos'.",
    points: 25,
    medal: '🔍 Recuperador',
  },
  {
    id: 54,
    title: 'Buscar Bug con Bisect',
    description:
      '¿Cuál es el comando para encontrar qué commit introdujo un bug?',
    scenario:
      'Tu app funciona en commit A pero no en commit B. Necesitas encontrar el culpable.',
    correctCommands: [
      'git bisect start',
      'git bisect good commit1',
      'git bisect bad commit2',
    ],
    hint: "Usa 'git bisect' para búsqueda binaria de bugs.",
    points: 30,
    medal: '🐛 Cazador',
  },
  {
    id: 55,
    title: 'Archivo .gitattributes',
    description: '¿Qué archivo controla cómo Git trata archivos específicos?',
    scenario: 'Quieres que Git normalice saltos de línea en Windows/Linux.',
    correctCommands: [
      'crear .gitattributes',
      '.gitattributes',
      'archivo .gitattributes',
    ],
    hint: "Crea '.gitattributes' para configurar atributos de archivos.",
    points: 20,
    medal: '⚙️ Atributos',
  },
  {
    id: 56,
    title: 'Pre-commit Hooks',
    description: '¿Qué son los hooks de Git y dónde se ubican?',
    scenario: 'Quieres que Git verifique linting antes de hacer commit.',
    correctCommands: [
      'crear archivo en .git/hooks',
      '.git/hooks/pre-commit',
      'hooks',
    ],
    hint: "Los hooks van en '.git/hooks/', ejecutan scripts antes de git commands.",
    points: 25,
    medal: '🪝 Gancho',
  },
  {
    id: 57,
    title: 'Notas en Commits (Git Notes)',
    description: '¿Cuál es el comando para agregar notas a un commit?',
    scenario: 'Quieres agregar contexto adicional a un commit antiguo.',
    correctCommands: [
      'git notes add -m "nota" commit-id',
      'git notes add commit-id',
    ],
    hint: "Usa 'git notes add' para agregar notas a commits.",
    points: 20,
    medal: '📝 Anotador',
  },
  {
    id: 58,
    title: 'Grep en Git',
    description:
      '¿Cuál es el comando para buscar texto en archivos rastreados?',
    scenario: 'Necesitas encontrar dónde se usa la función "loginUser".',
    correctCommands: ['git grep "loginUser"', 'git grep -n "loginUser"'],
    hint: "Es 'git grep' seguido del texto a buscar.",
    points: 20,
    medal: '🔎 Buscador',
  },
  {
    id: 59,
    title: 'Shortlog',
    description: '¿Cuál es el comando para ver contribuciones por autor?',
    scenario: 'Quieres ver cuántos commits hizo cada persona.',
    correctCommands: ['git shortlog', 'git shortlog -sn'],
    hint: "Es 'git shortlog' (usa -sn para ordenar por contribuciones).",
    points: 15,
    medal: '👥 Estadísticas',
  },
  {
    id: 60,
    title: 'Fsck (File System Check)',
    description:
      '¿Cuál es el comando para verificar integridad del repositorio?',
    scenario: 'Sospechas que hay corrupción en tu repositorio .git.',
    correctCommands: ['git fsck', 'git fsck --full'],
    hint: "Es 'git fsck' para verificar la integridad del archivo.",
    points: 20,
    medal: '🔧 Verificador',
  },
  {
    id: 61,
    title: 'Gc (Garbage Collection)',
    description: '¿Cuál es el comando para optimizar el repositorio?',
    scenario: 'Quieres comprimir y limpiar archivos innecesarios en .git.',
    correctCommands: ['git gc', 'git gc --aggressive'],
    hint: "Es 'git gc' para recolectar basura y optimizar.",
    points: 15,
    medal: '🧹 Limpiador',
  },
  {
    id: 62,
    title: 'Verificar Objeto Git',
    description: '¿Cuál es el comando para examinar un objeto Git?',
    scenario: 'Necesitas saber qué contiene un commit específico.',
    correctCommands: ['git cat-file -p abc123', 'git cat-file commit abc123'],
    hint: "Usa 'git cat-file -p' para ver contenido de objetos Git.",
    points: 20,
    medal: '🔬 Inspector',
  },
  {
    id: 63,
    title: 'Listar Objetos Git',
    description:
      '¿Cuál es el comando para listar todos los objetos del repositorio?',
    scenario: 'Quieres ver todos los blobs, commits y trees del proyecto.',
    correctCommands: [
      'git rev-list --all --objects',
      'git rev-list HEAD --all',
    ],
    hint: "Usa 'git rev-list --all --objects'.",
    points: 20,
    medal: '📦 Catalogador',
  },
  {
    id: 64,
    title: 'Replace (Reemplazar Objetos)',
    description: '¿Cuál es el comando para reemplazar un objeto Git?',
    scenario: 'Necesitas reemplazar un commit sin cambiar su ID.',
    correctCommands: [
      'git replace commit-viejo commit-nuevo',
      'git replace objeto reemplazo',
    ],
    hint: "Usa 'git replace' para alias de objetos Git.",
    points: 25,
    medal: '🔄 Reemplazador',
  },
  {
    id: 65,
    title: 'Count Objects',
    description: '¿Cuál es el comando para contar objetos y calcular tamaño?',
    scenario: 'Quieres saber cuánto espacio ocupa tu repositorio.',
    correctCommands: ['git count-objects -v', 'git count-objects'],
    hint: "Usa 'git count-objects -v' para detalles.",
    points: 15,
    medal: '💾 Tamaño',
  },
  {
    id: 66,
    title: 'Verify Pack',
    description: '¿Cuál es el comando para verificar archivos pack?',
    scenario: 'Sospechas que hay corrupción en archivos comprimidos.',
    correctCommands: ['git verify-pack', 'git verify-pack -v pack-file'],
    hint: "Usa 'git verify-pack' para verificar integridad de packs.",
    points: 20,
    medal: '✓ Validador',
  },
  {
    id: 67,
    title: 'Prune (Eliminar Objetos Huérfanos)',
    description: '¿Cuál es el comando para eliminar objetos no referenciados?',
    scenario: 'Quieres liberar espacio eliminando commits no accesibles.',
    correctCommands: ['git prune', 'git prune -v'],
    hint: "Usa 'git prune' para eliminar objetos huérfanos.",
    points: 20,
    medal: '🗑️ Podador',
  },
  {
    id: 68,
    title: 'Format Patch',
    description: '¿Cuál es el comando para crear patches de commits?',
    scenario: 'Necesitas enviar cambios vía email en formato patch.',
    correctCommands: ['git format-patch main', 'git format-patch -1 HEAD'],
    hint: "Usa 'git format-patch' para generar archivos .patch.",
    points: 20,
    medal: '📧 Parchero',
  },
  {
    id: 69,
    title: 'Apply Patch',
    description: '¿Cuál es el comando para aplicar un archivo patch?',
    scenario: 'Recibiste un archivo .patch y necesitas aplicarlo.',
    correctCommands: ['git apply archivo.patch', 'git am archivo.patch'],
    hint: "Usa 'git apply' o 'git am' para patches.",
    points: 20,
    medal: '🔨 Aplicador',
  },
  {
    id: 70,
    title: 'Request Pull',
    description: '¿Cuál es el comando para generar solicitud de pull?',
    scenario: 'Necesitas comunicar cambios en un proyecto remoto.',
    correctCommands: [
      'git request-pull origin/main local-branch',
      'git request-pull start-commit end-commit',
    ],
    hint: "Usa 'git request-pull' para generar resumen de cambios.",
    points: 20,
    medal: '📮 Solicitador',
  },
  {
    id: 71,
    title: 'Submodule (Submódulos)',
    description:
      '¿Cuál es el comando para agregar un repositorio como submódulo?',
    scenario: 'Tu proyecto usa una librería en otro repositorio Git.',
    correctCommands: [
      'git submodule add url ruta',
      'git submodule add https://repo.git lib/',
    ],
    hint: "Usa 'git submodule add' para incluir otros repos.",
    points: 25,
    medal: '📦 Modular',
  },
  {
    id: 72,
    title: 'Clonar con Submódulos',
    description: '¿Cuál es el comando para clonar incluyendo submódulos?',
    scenario: 'Necesitas clonar un proyecto que tiene submódulos.',
    correctCommands: [
      'git clone --recurse-submodules url',
      'git clone --recursive url',
    ],
    hint: "Usa '--recurse-submodules' o '--recursive' al clonar.",
    points: 20,
    medal: '📥 Clonador Pro',
  },
  {
    id: 73,
    title: 'Actualizar Submódulos',
    description: '¿Cuál es el comando para actualizar submódulos?',
    scenario: 'Los submódulos tienen actualizaciones disponibles.',
    correctCommands: ['git submodule update --remote', 'git submodule update'],
    hint: "Usa 'git submodule update' con '--remote' para nuevo contenido.",
    points: 20,
    medal: '🔄 Sincronizador',
  },
  {
    id: 74,
    title: 'Worktree (Múltiples Árboles)',
    description:
      '¿Cuál es el comando para trabajar en múltiples ramas simultáneamente?',
    scenario: 'Necesitas trabajar en feature A y hotfix B sin cambiar de rama.',
    correctCommands: [
      'git worktree add ruta rama',
      'git worktree add ../hotfix hotfix-rama',
    ],
    hint: "Usa 'git worktree add' para crear espacios de trabajo adicionales.",
    points: 25,
    medal: '🌳 Árbol',
  },
  {
    id: 75,
    title: 'Ver Worktrees',
    description: '¿Cuál es el comando para listar worktrees activos?',
    scenario: 'Quieres saber qué worktrees tienes abiertos.',
    correctCommands: ['git worktree list', 'git worktree list -v'],
    hint: "Usa 'git worktree list'.",
    points: 15,
    medal: '📋 Listatodo',
  },
  {
    id: 76,
    title: 'Remover Worktree',
    description: '¿Cuál es el comando para eliminar un worktree?',
    scenario: 'Ya terminaste con un worktree y quieres borrarlo.',
    correctCommands: ['git worktree remove ruta', 'git worktree prune'],
    hint: "Usa 'git worktree remove' o 'prune' para limpiar.",
    points: 15,
    medal: '🗑️ Borrador',
  },
  {
    id: 77,
    title: 'Sparse Checkout',
    description: '¿Cuál es el comando para descargar solo ciertos archivos?',
    scenario: 'Tu repositorio es enorme y solo necesitas ciertos directorios.',
    correctCommands: [
      'git sparse-checkout init',
      'git sparse-checkout set ruta/',
    ],
    hint: "Usa 'git sparse-checkout' para checkout parcial.",
    points: 25,
    medal: '📂 Selectivo',
  },
  {
    id: 78,
    title: 'Shallow Clone',
    description: '¿Cuál es el comando para clonar solo historial reciente?',
    scenario: 'El repositorio es muy grande, solo necesitas últimos cambios.',
    correctCommands: ['git clone --depth 1 url', 'git clone --depth 10 url'],
    hint: "Usa '--depth N' para limitar profundidad del historial.",
    points: 20,
    medal: '⚡ Rápido',
  },
  {
    id: 79,
    title: 'Unshallow',
    description:
      '¿Cuál es el comando para convertir un clone shallow a completo?',
    scenario: 'Necesitas el historial completo de un clone shallow.',
    correctCommands: [
      'git fetch --unshallow',
      "git remote set-branches origin '*'",
    ],
    hint: "Usa 'git fetch --unshallow' para traer historial completo.",
    points: 20,
    medal: '📚 Completo',
  },
  {
    id: 80,
    title: 'LFS (Large File Storage)',
    description: '¿Cuál es el comando para usar Git LFS?',
    scenario: 'Tu proyecto tiene archivos binarios grandes (videos, imágenes).',
    correctCommands: ['git lfs install', 'git lfs track "*.mp4"'],
    hint: "Usa 'git lfs' para manejar archivos grandes.",
    points: 25,
    medal: '💿 Media',
  },
];

export function verifyCommand(
  command: string,
  correctCommands: string[]
): boolean {
  const cmd = command.trim().toLowerCase();
  return correctCommands.some((correct) => {
    if (cmd.includes('"') || cmd.includes("'")) {
      return (
        cmd === correct.toLowerCase() ||
        cmd === correct.toLowerCase().replace(/"/g, "'")
      );
    }
    return cmd.includes(correct.toLowerCase().split(' ').slice(0, 2).join(' '));
  });
}
